#!/usr/bin/env bash
# generate-reports.sh — Regenerate all lens leaderboards and update the index.
#
# Usage:
#   ./scripts/generate-reports.sh              # regenerate all
#   ./scripts/generate-reports.sh chat-app     # one lens only
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DB="$PROJECT_DIR/data/stack-explorer.db"
SE="$PROJECT_DIR/stack-explorer"
REPORTS="$PROJECT_DIR/reports"

FILTER="${1:-}"

# Get list of lenses
if [[ -n "$FILTER" ]]; then
  LENSES="$FILTER"
else
  LENSES=$(sqlite3 "$DB" "SELECT id FROM lenses ORDER BY name")
fi

echo "=== Generating Lens Reports ==="

for lens_id in $LENSES; do
  lens_name=$(sqlite3 "$DB" "SELECT name FROM lenses WHERE id = '$lens_id'")
  lens_desc=$(sqlite3 "$DB" "SELECT description FROM lenses WHERE id = '$lens_id'")
  dim_count=$(sqlite3 "$DB" "SELECT COUNT(*) FROM lens_dimensions WHERE lens_id = '$lens_id'")

  echo "Generating: $lens_name ($lens_id) — $dim_count dimensions"

  # Recalculate all scored repos through this lens
  sqlite3 "$DB" "SELECT id FROM scorecards" | while read sc_id; do
    sqlite3 "$DB" "
      UPDATE scorecards SET overall = (
        SELECT COALESCE(SUM(ds.score * ld.weight) / NULLIF(SUM(ld.weight), 0), 0)
        FROM dimension_scores ds
        JOIN lens_dimensions ld ON ld.dimension_id = ds.dimension_id AND ld.lens_id = '$lens_id'
        WHERE ds.scorecard_id = $sc_id
      ) WHERE id = $sc_id
    "
  done

  # Pull leaderboard data with recalculated overalls
  LEADERBOARD=$(sqlite3 -separator '|' "$DB" "
    SELECT r.id, r.name, r.category, r.stack, r.is_own, r.url,
      printf('%.1f', sc.overall) as overall,
      s.loc
    FROM repos r
    JOIN scorecards sc ON sc.repo_id = r.id
    LEFT JOIN snapshots s ON s.repo_id = r.id AND s.id = (SELECT MAX(id) FROM snapshots WHERE repo_id = r.id)
    WHERE sc.overall > 0
    ORDER BY sc.overall DESC
  ")

  # Get dimensions for this lens
  DIMS=$(sqlite3 -separator '|' "$DB" "
    SELECT ld.dimension_id, rd.name, printf('%.1f', ld.weight)
    FROM lens_dimensions ld
    JOIN review_dimensions rd ON rd.id = ld.dimension_id
    WHERE ld.lens_id = '$lens_id'
    ORDER BY ld.sort_order
  ")

  # Generate report
  REPORT="$REPORTS/leaderboard-${lens_id}.md"
  {
    echo "# Leaderboard: $lens_name"
    echo ""
    echo "*$lens_desc*"
    echo ""
    echo "*Generated $(date +%Y-%m-%d) | Lens: \`$lens_id\` | $dim_count dimensions*"
    echo ""
    echo "## Dimensions & Weights"
    echo ""
    echo "| Dimension | Weight |"
    echo "|-----------|--------|"
    echo "$DIMS" | while IFS='|' read did dname dweight; do
      echo "| $dname | $dweight |"
    done
    echo ""
    echo "## Rankings"
    echo ""
    echo "| Rank | Repo | Category | Stack | Own | Score | LoC |"
    echo "|------|------|----------|-------|-----|-------|-----|"

    rank=0
    echo "$LEADERBOARD" | while IFS='|' read id name cat stack is_own url score loc; do
      rank=$((rank + 1))
      own_marker=""
      if [[ "$is_own" == "1" ]]; then
        own_marker="\\*"
        name="**$name**"
      fi
      loc_fmt=""
      if [[ -n "$loc" && "$loc" != "" ]]; then
        if [[ "$loc" -ge 1000000 ]]; then
          loc_fmt="$(echo "$loc" | awk '{printf "%.1fM", $1/1000000}')"
        elif [[ "$loc" -ge 1000 ]]; then
          loc_fmt="$(echo "$loc" | awk '{printf "%.0fK", $1/1000}')"
        else
          loc_fmt="$loc"
        fi
      fi
      if [[ -n "$url" && "$url" != "" ]]; then
        echo "| $rank | [$name]($url) | $cat | $stack | $own_marker | $score | $loc_fmt |"
      else
        echo "| $rank | $name | $cat | $stack | $own_marker | $score | $loc_fmt |"
      fi
    done
    echo ""
    echo "*Generated by Stack Explorer | (c) Hollis Labs*"
  } > "$REPORT"

  echo "  -> $REPORT"
done

# Restore the agent-platform lens as default (since we overwrote overalls)
echo ""
echo "Restoring agent-platform overalls as default..."
sqlite3 "$DB" "SELECT id FROM scorecards" | while read sc_id; do
  sqlite3 "$DB" "
    UPDATE scorecards SET overall = (
      SELECT COALESCE(SUM(ds.score * ld.weight) / NULLIF(SUM(ld.weight), 0), 0)
      FROM dimension_scores ds
      JOIN lens_dimensions ld ON ld.dimension_id = ds.dimension_id AND ld.lens_id = 'agent-platform'
      WHERE ds.scorecard_id = $sc_id
    ) WHERE id = $sc_id
  "
done

echo ""
echo "=== Complete ==="
